/*
 * GhnPlcLogger.cpp
 *
 *  Created on: May 31, 2016
 *      Author: tsokalo
 */

#include "ghn-plc-logger.h"

namespace ns3
{
namespace ghn {
GhnPlcLogger::GhnPlcLogger ()
{

}

GhnPlcLogger::~GhnPlcLogger ()
{

}


void
GhnPlcLogger::SetupLog (FileLogData logData)
{
  // Configure the file to be written.
  m_fileHelper.ConfigureFile (logData.fileName, FileAggregator::FORMATTED);

  // Set the labels for this formatted output file.
  m_fileHelper.Set2dFormat (logData.format);

  // Write the values generated by the probe.  The path that we
  // provide helps to disambiguate the source of the trace.
  m_fileHelper.WriteProbe (logData.typeId, logData.path, logData.probeTraceSource);
}
}
}
