# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('plc-fd-csma-cd-example', ['plc-fd','plc'])
    obj.source = 'plc-fd-csma-cd-example.cc'
    
def build(bld):
    obj = bld.create_ns3_program('plc-fd-phy-example', ['plc-fd','plc'])
    obj.source = 'plc-fd-phy-example.cc'
    
    