# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('in-home-topology', ['core'])
    module.source = [
        'model/in-home-topology.cc',
        'helper/in-home-topology-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('in-home-topology')
    module_test.source = [
        'test/in-home-topology-test-suite.cc',
        ]

    headers = bld(features=['ns3header'])
    headers.module = 'in-home-topology'
    headers.source = [
        'model/in-home-topology.h',
        'model/in-home-latex.h',
        'model/in-home-header.h',
        'helper/in-home-topology-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

