# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('plc-electrical-device', ['core', 'ghn-plc'])
    module.source = [
        'model/plc-electrical-device.cc',
        'model/plc-defs-extension.cpp',
        'model/water-filling.cc',
        'model/plc-max-rate.cc',
        'model/plc-max-rate-phy.cc',        
        'helper/plc-electrical-device-helper.cc',               
        ]

    module_test = bld.create_ns3_module_test_library('plc-electrical-device')
    module_test.source = [
        'test/plc-electrical-device-test-suite.cc',
        ]

    headers = bld(features=['ns3header'])
    headers.module = 'plc-electrical-device'
    headers.source = [
        'model/plc-electrical-device.h',
        'model/plc-defs-extension.h',
        'model/water-filling.h',
        'model/plc-max-rate.h',
        'model/plc-max-rate-phy.h',
        'helper/plc-electrical-device-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

