# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('ghn-plc-example', ['ghn-plc'])
    obj.source = 'ghn-plc-example.cc'
    
    obj = bld.create_ns3_program('ghn-plc-bit-loading-example', ['ghn-plc'])
    obj.source = 'ghn-plc-bit-loading-example.cc'    
    
    

